### ISSUE TITLE
Doesn't appear to work in macos 10.12 Sierra

### ISSUE THREAD

**Issue by satmandu** [emin/WebPQuickLook#8]
Quicklook on a webp just gives a blank screen now.

**Comment by derek73** [comment]
works for me on Sierra 10.12.3

**Comment by emin** [comment]
I reproduce the issue and the reason was that another application's quicklook plugin, in my case Pixelmator quicklook plugin (it's not under ~/Library/QuickLook), it's broken and can't generate quicklook previews for webp. It comes with application and somehow it registers public.webp UTI type to itself and making macOS to use that generator.

This plugin seems working fine, after removing Pixelmator's plugin files (actually I moved it to another directory).

### How do you know what's the issue for you ?

First enable quicklook logging by entering below command into terminal;

`defaults write -g QLEnableLogging YES`

Then open Console app and watch it while trying to quicklook a webp file. You'll see similar error logs to this;

<img width="1115" alt="screen shot 2017-04-19 at 09 23 26" src="https://cloud.githubusercontent.com/assets/326255/25166021/e846012c-24e1-11e7-8071-79aa3913c7a8.png">
 

As you can see it says which plugin it uses and if it's the case like this,  try to move that generator to another directory and then see if it works with this plugin.

Note: Make sure you reset qlmanage while doing these changes.

`qlmanage -r`

and in some cases it isn't enough to reset it, I kill Finder by doing;

`killall Finder`

don't worry it'll restart and go to where you were before

**Comment by emin** [comment]
This is the screenshot to prove that it works with this plugin;

<img width="1271" alt="screen shot 2017-04-19 at 09 32 04" src="https://cloud.githubusercontent.com/assets/326255/25166254/1d1f31c4-24e3-11e7-86c6-ac7e7ef635c8.png">
